### ISSUE TITLE
Cadastros de Aplicativo.

### ISSUE THREAD

**Issue by DiegoNanzer** [nomellini/DatamaceReactUI#11]
Ao incluir um  App,  a tela não esta enviando a lista de autorizações do app, ocasionando um erro na Api. 
Agora esse campo é obrigatório., portanto não ocasionará mais erro na Api, porém a tela tem que passar essa informação. 
 
Como a tela tem que saber quais autorizações o APP tem que ter? 
R: Para isso eu criei uma novar Api que devolve uma lista de chave/valor. 

Caminho da Api : /api/v1/Aplicativo/GetAutorizacoes

Sugiro colocar em check box. Pois o App pode ter mais que uma autorização.

**Comment by nomellini** [comment]
Implementado.
